#include <bridge.h>

#include "Luau/Ast.h"
#include "Luau/Cst.h"

using namespace Luau;

// AST
ZIG_EXPORT const unsigned char AstAttrIndex = AstAttr::ClassIndex();
ZIG_EXPORT const unsigned char AstGenericTypeIndex = AstGenericType::ClassIndex();
ZIG_EXPORT const unsigned char AstGenericTypePackIndex = AstGenericTypePack::ClassIndex();
ZIG_EXPORT const unsigned char AstExprGroupIndex = AstExprGroup::ClassIndex();
ZIG_EXPORT const unsigned char AstExprConstantNilIndex = AstExprConstantNil::ClassIndex();
ZIG_EXPORT const unsigned char AstExprConstantBoolIndex = AstExprConstantBool::ClassIndex();
ZIG_EXPORT const unsigned char AstExprConstantNumberIndex = AstExprConstantNumber::ClassIndex();
ZIG_EXPORT const unsigned char AstExprConstantStringIndex = AstExprConstantString::ClassIndex();
ZIG_EXPORT const unsigned char AstExprLocalIndex = AstExprLocal::ClassIndex();
ZIG_EXPORT const unsigned char AstExprGlobalIndex = AstExprGlobal::ClassIndex();
ZIG_EXPORT const unsigned char AstExprVarargsIndex = AstExprVarargs::ClassIndex();
ZIG_EXPORT const unsigned char AstExprCallIndex = AstExprCall::ClassIndex();
ZIG_EXPORT const unsigned char AstExprIndexNameIndex = AstExprIndexName::ClassIndex();
ZIG_EXPORT const unsigned char AstExprIndexExprIndex = AstExprIndexExpr::ClassIndex();
ZIG_EXPORT const unsigned char AstExprFunctionIndex = AstExprFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstExprTableIndex = AstExprTable::ClassIndex();
ZIG_EXPORT const unsigned char AstExprUnaryIndex = AstExprUnary::ClassIndex();
ZIG_EXPORT const unsigned char AstExprBinaryIndex = AstExprBinary::ClassIndex();
ZIG_EXPORT const unsigned char AstExprTypeAssertionIndex = AstExprTypeAssertion::ClassIndex();
ZIG_EXPORT const unsigned char AstExprIfElseIndex = AstExprIfElse::ClassIndex();
ZIG_EXPORT const unsigned char AstExprInterpStringIndex = AstExprInterpString::ClassIndex();
ZIG_EXPORT const unsigned char AstStatBlockIndex = AstStatBlock::ClassIndex();
ZIG_EXPORT const unsigned char AstStatIfIndex = AstStatIf::ClassIndex();
ZIG_EXPORT const unsigned char AstStatWhileIndex = AstStatWhile::ClassIndex();
ZIG_EXPORT const unsigned char AstStatRepeatIndex = AstStatRepeat::ClassIndex();
ZIG_EXPORT const unsigned char AstStatBreakIndex = AstStatBreak::ClassIndex();
ZIG_EXPORT const unsigned char AstStatContinueIndex = AstStatContinue::ClassIndex();
ZIG_EXPORT const unsigned char AstStatReturnIndex = AstStatReturn::ClassIndex();
ZIG_EXPORT const unsigned char AstStatExprIndex = AstStatExpr::ClassIndex();
ZIG_EXPORT const unsigned char AstStatLocalIndex = AstStatLocal::ClassIndex();
ZIG_EXPORT const unsigned char AstStatForIndex = AstStatFor::ClassIndex();
ZIG_EXPORT const unsigned char AstStatForInIndex = AstStatForIn::ClassIndex();
ZIG_EXPORT const unsigned char AstStatAssignIndex = AstStatAssign::ClassIndex();
ZIG_EXPORT const unsigned char AstStatCompoundAssignIndex = AstStatCompoundAssign::ClassIndex();
ZIG_EXPORT const unsigned char AstStatFunctionIndex = AstStatFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstStatLocalFunctionIndex = AstStatLocalFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstStatTypeAliasIndex = AstStatTypeAlias::ClassIndex();
ZIG_EXPORT const unsigned char AstStatTypeFunctionIndex = AstStatTypeFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstStatDeclareFunctionIndex = AstStatDeclareFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstStatDeclareGlobalIndex = AstStatDeclareGlobal::ClassIndex();
ZIG_EXPORT const unsigned char AstStatDeclareExternTypeIndex = AstStatDeclareExternType::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeReferenceIndex = AstTypeReference::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeTableIndex = AstTypeTable::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeFunctionIndex = AstTypeFunction::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeTypeofIndex = AstTypeTypeof::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeOptionalIndex = AstTypeOptional::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeUnionIndex = AstTypeUnion::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeIntersectionIndex = AstTypeIntersection::ClassIndex();
ZIG_EXPORT const unsigned char AstExprErrorIndex = AstExprError::ClassIndex();
ZIG_EXPORT const unsigned char AstStatErrorIndex = AstStatError::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeErrorIndex = AstTypeError::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeSingletonBoolIndex = AstTypeSingletonBool::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeSingletonStringIndex = AstTypeSingletonString::ClassIndex();
ZIG_EXPORT const unsigned char AstTypeGroupIndex = AstTypeGroup::ClassIndex();
ZIG_EXPORT const unsigned char AstTypePackExplicitIndex = AstTypePackExplicit::ClassIndex();
ZIG_EXPORT const unsigned char AstTypePackVariadicIndex = AstTypePackVariadic::ClassIndex();
ZIG_EXPORT const unsigned char AstTypePackGenericIndex = AstTypePackGeneric::ClassIndex();

// CST
ZIG_EXPORT const unsigned char CstExprConstantNumberIndex = CstExprConstantNumber::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprConstantStringIndex = CstExprConstantString::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprCallIndex = CstExprCall::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprIndexExprIndex = CstExprIndexExpr::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprFunctionIndex = CstExprFunction::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprTableIndex = CstExprTable::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprOpIndex = CstExprOp::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprTypeAssertionIndex = CstExprTypeAssertion::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprIfElseIndex = CstExprIfElse::CstClassIndex();
ZIG_EXPORT const unsigned char CstExprInterpStringIndex = CstExprInterpString::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatDoIndex = CstStatDo::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatRepeatIndex = CstStatRepeat::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatReturnIndex = CstStatReturn::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatLocalIndex = CstStatLocal::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatForIndex = CstStatFor::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatForInIndex = CstStatForIn::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatAssignIndex = CstStatAssign::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatCompoundAssignIndex = CstStatCompoundAssign::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatFunctionIndex = CstStatFunction::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatLocalFunctionIndex = CstStatLocalFunction::CstClassIndex();
ZIG_EXPORT const unsigned char CstGenericTypeIndex = CstGenericType::CstClassIndex();
ZIG_EXPORT const unsigned char CstGenericTypePackIndex = CstGenericTypePack::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatTypeAliasIndex = CstStatTypeAlias::CstClassIndex();
ZIG_EXPORT const unsigned char CstStatTypeFunctionIndex = CstStatTypeFunction::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeReferenceIndex = CstTypeReference::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeTableIndex = CstTypeTable::CstClassIndex();
ZIG_EXPORT const int CstTypeTableItemKindIndexer = static_cast<int>(CstTypeTable::Item::Kind::Indexer);
ZIG_EXPORT const int CstTypeTableItemKindProperty = static_cast<int>(CstTypeTable::Item::Kind::Property);
ZIG_EXPORT const int CstTypeTableItemKindStringProperty = static_cast<int>(CstTypeTable::Item::Kind::StringProperty);
ZIG_EXPORT const unsigned char CstTypeFunctionIndex = CstTypeFunction::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeTypeofIndex = CstTypeTypeof::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeUnionIndex = CstTypeUnion::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeIntersectionIndex = CstTypeIntersection::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypeSingletonStringIndex = CstTypeSingletonString::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypePackExplicitIndex = CstTypePackExplicit::CstClassIndex();
ZIG_EXPORT const unsigned char CstTypePackGenericIndex = CstTypePackGeneric::CstClassIndex();
