name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.2540+f857bf72e
        use-cache: false

    - name: Run tests
      run: make test
